[package]
build = "build.rs"
edition = "2021"
name = "lox"
rust-version = "1.58"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.0.6", features = ["derive"] }
codespan-reporting = "0.11.1"
fnv = "1.0.7"
gc = { version = "0.4.1", features = ["derive"] }
human-panic = "1.0.3"
iota = "0.2.2"
lalrpop-util = "0.19.6"
logos = "0.12.0"
mimalloc = { version = "0.1.27", default-features = false }
pprof = { version = "0.6.2", features = [
    "flamegraph",
    "protobuf",
], optional = true }
rustyline = "9.1.2"
thiserror = "1.0.30"

[build-dependencies]
lalrpop = { version = "0.19.1", default-features = false }

[dev-dependencies]
regex = { version = "1.5.4", default-features = false, features = ["std"] }
test-generator = "0.3.0"

[profile.release]
# codegen-units = 1
# lto = true
# strip = true

[features]
profiler = ["pprof"]
