[package]
authors = [
    "Ajeet D'Souza <98ajeet@gmail.com>",
    "Kartik Sharma <kartik.sharma522@gmail.com>",
]
description = "A compiler, VM, language server, and online playground for the Lox programming language"
edition = "2021"
keywords = ["compiler", "interpreter", "language", "lox", "vm"]
license = "MIT"
name = "loxcraft"
repository = "https://github.com/ajeetdsouza/loxcraft"
rust-version = "1.65"
version = "0.1.0"

[badges]
maintenance = { status = "actively-developed" }

[workspace]
members = ["crates/*", "xtask"]

[workspace.dependencies]
anyhow = "1.0.52"
arrayvec = "0.7.2"
askama_escape = "0.10.3"
build-deps = "0.1.4"
cc = "1.0.73"
clap = { version = "4.0.0", features = ["derive"] }
codespan-reporting = "0.11.1"
console_error_panic_hook = "0.1.1"
dirs = "4.0.0"
hashbrown = { version = "0.13.1", default-features = false, features = [
    "inline-more",
] }
http = "0.2.6"
human-panic = "1.0.3"
iota = "0.2.2"
lalrpop = { version = "0.19.1", default-features = false }
lalrpop-util = "0.19.6"
logos = "0.12.0"
mimalloc = { version = "0.1.27", default-features = false }
nu-ansi-term = "0.46.0"
pretty_assertions = "1.1.0"
reedline = "0.14.0"
rust-embed = { version = "6.4.0", features = ["include-exclude"] }
rustc-hash = "1.1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
termcolor = "1.1.3"
test-generator = "0.3.0"
thiserror = "1.0.34"
tokio = { version = "1.17.0", features = ["io-std", "rt"] }
tower-lsp = "0.17.0"
tree-sitter = "0.20.4"
tree-sitter-highlight = "0.20.1"
warp = "0.3.2"
wasm-bindgen = "0.2.80"
webbrowser = "0.8.0"

[features]
default = ["lsp", "playground", "repl"]
gc-off = ["lox-vm/gc-off"]
gc-stress = ["lox-vm/gc-stress"]
gc-trace = ["lox-vm/gc-trace"]
lsp = ["dep:lox-lsp"]
playground = ["dep:lox-playground"]
repl = ["dep:lox-repl"]
vm-trace = ["lox-vm/vm-trace"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
dirs.workspace = true
human-panic.workspace = true
lox-common.path = "crates/lox-common"
lox-lsp = { path = "crates/lox-lsp", optional = true }
lox-playground = { path = "crates/lox-playground", optional = true }
lox-repl = { path = "crates/lox-repl", optional = true }
lox-syntax.path = "crates/lox-syntax"
lox-vm.path = "crates/lox-vm"
termcolor.workspace = true

[profile.release]
codegen-units = 1
debug = 0
lto = true
panic = "abort"
strip = true

[profile.profiling]
inherits = "release"
debug = 1
strip = false
