[package]
authors = [
    "Ajeet D'Souza <98ajeet@gmail.com>",
    "Kartik Sharma <kartik.sharma522@gmail.com>",
]
description = "A compiler / VM for the Lox programming language"
edition = "2021"
keywords = ["compiler", "interpreter", "language", "lox", "vm"]
license = "MIT"
name = "lox"
repository = "https://github.com/ajeetdsouza/lox"
rust-version = "1.61"
version = "0.1.0"

[badges]
maintenance = { status = "actively-developed" }

[workspace]
members = [
    "crates/lox-playground",
    "crates/lox-syntax",
    "crates/lox-vm",
    "crates/tree-sitter-lox",
]

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.1.0", features = ["derive"] }
crossterm = "0.23.2"
dirs = "4.0.0"
human-panic = "1.0.3"
lox-playground = { path = "crates/lox-playground" }
lox-syntax = { path = "crates/lox-syntax" }
lox-vm = { path = "crates/lox-vm" }
mimalloc = { version = "0.1.27", default-features = false }
nu-ansi-term = "0.45.0"
reedline = "0.6.0"
tree-sitter-highlight = "0.20.1"
tree-sitter-lox = { path = "crates/tree-sitter-lox", version = "*" }

[dev-dependencies]
pretty_assertions = "1.1.0"
test-generator = "0.3.0"

[profile.dev]
debug = 0

[profile.release]
codegen-units = 1
debug = 0
lto = true
strip = true
