[package]
edition = "2021"
name = "lox-playground"
version = "0.1.0"

[dependencies]
anyhow.workspace = true
http.workspace = true
rust-embed.workspace = true
tokio.workspace = true
warp.workspace = true
webbrowser.workspace = true
