[package]
edition = "2021"
name = "lox-playground"
version = "0.1.0"

[dependencies]
http = "0.2.6"
rust-embed = { version = "6.4.0", features = ["include-exclude"] }
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
warp = "0.3.2"
webbrowser = "0.7.1"
