[package]
name = "lox-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.1"
lox-vm = { path = "../lox-vm" }
lox-syntax = { path = "../lox-syntax" }
wasm-bindgen = "0.2.79"
web-sys = { version = "0.3.56", features = ["Document", "Element", "Window"] }
