[package]
edition = "2021"
name = "lox-vm"
version = "0.1.0"

[dependencies]
codespan-reporting = "0.11.1"
fxhash = "0.2.1"
lox-syntax = { path = "../lox-syntax" }
termcolor = "1.1.3"
thiserror = "1.0.30"
