[package]
edition = "2021"
name = "lox-vm"
version = "0.1.0"

[dependencies]
anyhow = "1.0.52"
codespan-reporting = "0.11.1"
fnv = "1.0.7"
lox-syntax = { path = "../lox-syntax" }
termcolor = "1.1.3"
thiserror = "1.0.30"
