[package]
name = "lox-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = { version = "0.12.3", features = [
    "inline-more",
], default-features = false }
iota = "0.2.2"
lox-syntax = { path = "../lox-syntax" }
rustc-hash = "1.1.0"
