[package]
edition = "2021"
name = "lox-syntax"
version = "0.1.0"

[dependencies]
lalrpop-util = "0.19.6"
logos = "0.12.0"
lox-common = { path = "../lox-common" }

[build-dependencies]
lalrpop = { version = "0.19.1", default-features = false }

[dev-dependencies]
pretty_assertions = "1.1.0"
