[package]
name = "lox-syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = "0.19.6"
logos = "0.12.0"

[build-dependencies]
lalrpop = { version = "0.19.1", default-features = false }
