[package]
edition = "2021"
name = "lox-syntax"
version = "0.1.0"

[dependencies]
lalrpop-util.workspace = true
logos.workspace = true
lox-common.path = "../lox-common"

[build-dependencies]
lalrpop.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
