[package]
edition = "2021"
name = "lox-syntax"
version = "0.1.0"

[dependencies]
codespan-reporting = "0.11.1"
lalrpop-util = "0.19.6"
logos = "0.12.0"

[build-dependencies]
lalrpop = { version = "0.19.1", default-features = false }

[dev-dependencies]
pretty_assertions = "1.1.0"
