default:
  @just --list

build:
    wasm-pack build --out-dir=pkg/ --release --target=web

clean:
    rm -rf pkg/
    cargo clean

fmt:
    cargo +nightly fmt --all

lint:
    cargo +nightly fmt --all -- --check
    cargo clippy --all-features --all-targets --workspace -- --deny=warnings
