name: ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          profile: minimal
          toolchain: 1.78.0
      - name: Install Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          profile: minimal
          toolchain: nightly
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: playground/package-lock.json
          node-version: 18
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Install just + wasm-pack
        uses: taiki-e/install-action@v2
        with:
          tool: just,wasm-pack
      - name: Run linters
        run: just lint-all
  test-miri:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        partition: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: miri
          profile: minimal
          toolchain: nightly
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Install cargo-nextest + just
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,just
      - name: Run tests
        run: just test-miri --no-fail-fast --partition=count:${{ matrix.partition }}/8 --test-threads=num-cpus
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Install cargo-nextest + just
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,just
      - name: Run tests
        run: just test --no-fail-fast
