name: ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
          toolchain: nightly
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.85
        with:
          components: clippy
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: playground/package.json
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          cache-dependency-path: playground/pnpm-lock.yaml
          node-version: 18
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Run linters
        run: task lint
  test-miri:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        partition: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run tests
        run: task test-miri -- --no-fail-fast --partition=count:${{ matrix.partition }}/8 --test-threads=num-cpus
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.85
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run tests
        run: task test -- --no-fail-fast
