name: ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
env:
  CARGO_INCREMENTAL: 0
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          profile: minimal
          toolchain: stable
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Install cargo-audit
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: 0.16.0
      - name: Install wasm-pack
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: 0.10.2
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --color=always --files-with-diff
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-features --all-targets --color=always -- --deny=warnings
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features --all-targets --color=always --no-fail-fast
      - name: cargo audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
          args: --color=always --deny=warnings
